# Generated by Django 3.2.16 on 2023-01-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, null=True, verbose_name='Слово')),
                ('type', models.CharField(blank=True, choices=[(None, 'Выберите тип слова'), ('v', 'Verb (сущ.)'), ('n', 'Noun (глаг.)'), ('a', 'Adjective (прил.)')], max_length=1)),
                ('translation', models.CharField(max_length=25, verbose_name='Перевод')),
                ('discription', models.TextField(blank=True, verbose_name='Доп. комментарий к переводу')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addwords.language', verbose_name='Язык')),
            ],
        ),
    ]
