# Generated by Django 4.1.6 on 2023-03-24 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addwords', '0002_word_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='words', to='addwords.language', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='word',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='+', to='addwords.word', verbose_name='Синонимы'),
        ),
        migrations.AlterField(
            model_name='word',
            name='type',
            field=models.CharField(blank=True, choices=[(None, 'Выберите тип слова'), ('Verb', 'Verb (сущ.)'), ('Noun', 'Noun (глаг.)'), ('Adjective', 'Adjective (прил.)')], max_length=10),
        ),
        migrations.CreateModel(
            name='AdvUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
