# Generated by Django 4.1.6 on 2023-03-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addwords', '0003_alter_word_language_alter_word_synonyms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Языки'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'Слово', 'verbose_name_plural': 'Слова'},
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('word', 'language')},
        ),
    ]
