# Generated by Django 4.1.6 on 2023-03-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addwords', '0009_word_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='img',
            field=models.ImageField(blank=True, help_text='Картинка, которая поможеть запомнить слово.', null=True, upload_to='for_words', verbose_name='Изображение'),
        ),
    ]
