# Generated by Django 4.1.6 on 2023-03-29 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addwords', '0010_word_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Кто добавил слово', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_words', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
