# Generated by Django 4.1.6 on 2023-03-29 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addwords', '0011_alter_word_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('IN', 'In progress'), ('RE', 'Rejected'), ('AC', 'Accepted')], max_length=15)),
                ('from_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exchanges_from', to=settings.AUTH_USER_MODEL, verbose_name='От пользователя')),
                ('to_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exchanges_to', to=settings.AUTH_USER_MODEL, verbose_name='Пользователю')),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exchanges_in', to='addwords.word', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Обмен словами',
                'verbose_name_plural': 'Обмены словами',
                'ordering': ['date'],
            },
        ),
    ]
