# Generated by Django 4.1.6 on 2023-03-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addwords', '0012_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='status',
            field=models.CharField(choices=[('IN', 'In progress'), ('RE', 'Rejected'), ('AC', 'Accepted')], default='IN', max_length=15),
        ),
    ]
