# Generated by Django 4.1.6 on 2023-03-29 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addwords', '0013_alter_exchange_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_from', to=settings.AUTH_USER_MODEL, verbose_name='От пользователя'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_to', to=settings.AUTH_USER_MODEL, verbose_name='Пользователю'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_in', to='addwords.word', verbose_name='Слово'),
        ),
    ]
