# Generated by Django 4.1.6 on 2023-04-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addwords', '0015_category_order_product_alter_word_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='is_saller',
        ),
    ]
