# Generated by Django 4.1.6 on 2023-04-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addwords', '0016_remove_advuser_is_saller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='archived',
            field=models.BooleanField(default=False, help_text='Будет ли слово отображаться в каталоге?', verbose_name='Архивировано'),
        ),
    ]
