# Generated by Django 4.1.6 on 2023-04-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addwords', '0018_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='saller',
            new_name='seller',
        ),
    ]
