# Generated by Django 4.1.6 on 2023-04-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
