# Generated by Django 4.2.3 on 2023-08-04 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(None, 'Choose order status'), ('IN', 'In progress'), ('RE', 'Rejected'), ('FI', 'Finished')], default='IN', max_length=30)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_from', to=settings.AUTH_USER_MODEL, verbose_name='От пользователя')),
                ('products', models.ManyToManyField(help_text='Товары, составляющие заказ.', to='products.product', verbose_name='Товары')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_to', to=settings.AUTH_USER_MODEL, verbose_name='Пользователю')),
            ],
            options={
                'verbose_name': 'Заказ пользователя',
                'verbose_name_plural': 'Заказы пользователей',
            },
        ),
    ]
