# Generated by Django 4.2.3 on 2023-08-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='stage_status',
        ),
    ]
